"""Open a persistent Chromium profile so the operator can Douyin QR-login once."""

from __future__ import annotations

import logging
import time
from pathlib import Path

from dylive.config import AppConfig
from dylive.exceptions import OperatorRequiredError

log = logging.getLogger("dylive.login")

CREATOR_HOME = "https://creator.douyin.com/"
UPLOAD_URL = "https://creator.douyin.com/creator-micro/content/upload"

LOGIN_MARKERS = ("扫码登录", "验证码登录", "密码登录", "手机号登录", "登录即代表同意")
CHALLENGE_MARKERS = ("请完成验证", "安全验证", "验证码", "captcha", "短信验证", "二步验证")


def login(cfg: AppConfig, *, export_cookies: bool = True, timeout: float = 300.0) -> Path:
    """Headed browser; operator scans QR. Cookies optionally exported to cookies.txt."""
    from playwright.sync_api import sync_playwright

    cfg.paths.ensure()
    profile = cfg.paths.browser_profile
    profile.mkdir(parents=True, exist_ok=True)
    log.info("打开抖音创作者中心。请用抖音 App 扫码登录。资料目录: %s", profile)
    log.info("登录完成后保持窗口，程序会自动检测；如需验证码/2FA 请在浏览器里完成。")

    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(profile),
            headless=False,
            viewport={"width": 1280, "height": 800},
            locale="zh-CN",
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = context.pages[0] if context.pages else context.new_page()
        page.goto(CREATOR_HOME, wait_until="domcontentloaded", timeout=60_000)
        deadline = time.time() + timeout
        logged_in = False
        while time.time() < deadline:
            _dismiss_modals(page)
            html = ""
            try:
                html = page.content()
            except Exception:
                pass
            url = page.url
            if _is_challenge(html):
                log.warning("检测到验证码 / 2FA / 安全验证。请在浏览器窗口里完成，然后等待。")
            if _is_logged_in(url, html):
                logged_in = True
                break
            time.sleep(2)
        if not logged_in:
            context.close()
            raise OperatorRequiredError(
                "登录超时。请再跑 dylive login，在打开的窗口里用抖音 App 扫码。"
            )
        log.info("已登录: %s", page.url)
        if export_cookies:
            _export_netscape(context.cookies(), cfg.paths.cookies)
            log.info("已导出 cookies → %s（供 yt-dlp / 直播页使用）", cfg.paths.cookies)
        context.close()
    return profile


def _is_logged_in(url: str, html: str) -> bool:
    if "creator-micro" in url and not any(m in html for m in LOGIN_MARKERS):
        return True
    if "creator.douyin.com" in url and "upload" in url:
        return True
    # Logged-in home often shows 作品 or 发布
    if "creator.douyin.com" in url and any(x in html for x in ("发布视频", "内容管理", "数据中心", "创作者中心")):
        if not any(m in html for m in LOGIN_MARKERS):
            return True
    return False


def _is_challenge(html: str) -> bool:
    low = html.lower()
    return any(m.lower() in low for m in CHALLENGE_MARKERS)


def _dismiss_modals(page) -> None:
    try:
        page.evaluate(
            """() => {
              const labels = ['我知道了', '知道了', '关闭', '暂不', '取消'];
              for (const text of labels) {
                const el = Array.from(document.querySelectorAll('button,[role="button"]'))
                  .find((n) => (n.textContent || '').trim() === text);
                if (el) el.click();
              }
            }"""
        )
    except Exception:
        pass


def _export_netscape(cookies: list[dict], dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by dylive login. Do not commit this file.",
    ]
    for c in cookies:
        domain = c.get("domain") or ""
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = str(int(c.get("expires") or 0))
        name = c.get("name") or ""
        value = c.get("value") or ""
        if not name:
            continue
        prefix = "#HttpOnly_" if c.get("httpOnly") else ""
        lines.append(f"{prefix}{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
